### ISSUE TITLE
nsepy get_history not responding - timeout occurs

### ISSUE THREAD

**Issue by vrp-selvam** [swapniljariwala/nsepy#114]
Hi,

I am trying to get the history of quotes using get_history, it was working sometime back but not responding now.

getting following error after waiting for long time

Error getting values HTTPConnectionPool(host='www.nseindia.com', port=80): Max retries exceeded with url: /marketinfo/sym_map/symbolCount.jsp?symbol=ADANIPORTS (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002042AEDE0C8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

thanks for your response.

**Comment by mbmarx** [comment]
@swapniljariwala the same error i am getting , it looks you have updated package 17days ago and committed changes two days back ,i have installed the changes to latest still i am getting the above mentioned error @vrp-selvam 
Is this solvable ,How to make the NSEPY working again. Any one Any suggestion please help.

**Comment by sarwankx** [comment]
@swapniljariwala  I am also getting timeout while waiting for get_history for fetching NSE options historical data. Few days back it was working. What I could debug was that nse have changed migrated their urls from www.nseindia.com to www1.nseindia.com , and hence it was not working. So, i updated the package to latest version but still it is not working. @swapniljariwala can I get your phone number or pls ping me in whatspp at +919632350035. I want to contribute to the project.

**Comment by vishaldamani** [comment]
Can someone please help me how to solve this error

>>> 
================ RESTART: D:\OneDrive\PythonPrograms\bhavcopy.py ===============
Traceback (most recent call last):
  File "D:\OneDrive\PythonPrograms\bhavcopy.py", line 4, in <module>
    prices = get_price_list(date(2015,1,1))
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\nsepy\history.py", line 309, in get_price_list
    txt =  unzip_str(res.content)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\nsepy\commons.py", line 122, in unzip_str
    zf = zipfile.ZipFile(file=fp)
  File "C:\Program Files (x86)\Python38-32\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Program Files (x86)\Python38-32\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
>>>

**Comment by mbmarx** [comment]
@swapniljariwala @sarwankx  can you please look at this issue and provide some solution .All of us waiting now. Some working solution is needed . 

**Others please confirm if you could fetch the data as on 31-JAN-2020**

**Comment by subinoy** [comment]
NSEpy is working fine as of 31st Jan. Could you post what's error you are
facing? You can't get 31st Jan price yet through get_history method. But
you can use get_price_list for that.
Rest is fine. Go through the thread, there is a solution which was
previously an issue.

Best,
Subinoy

**Comment by mbmarx** [comment]
@subinoy @swapniljariwala  the start of this thread has the error message the same error message i am getting  @vrp-selvam .
Not even able to fetch any data only the error comes.

Which is the solution you are referring to can you pls link the details here to check once again.

I deleted complete package and reinstalled from the updated Branch tag still  i am facing this issue.

**Comment by subinoy** [comment]
https://github.com/swapniljariwala/nsepy/issues/113

read the whole thread to solve the issue as it's changed the nsepy package
installation issue now(master branch working fine). Also, read the nsepy
documentation.

Best,
Subinoy

**Comment by siddcyber** [comment]
> Can someone please help me how to solve this error
> 
> > > >
> 
> ================ RESTART: D:\OneDrive\PythonPrograms\bhavcopy.py =============== Traceback (most recent call last): File "D:\OneDrive\PythonPrograms\bhavcopy.py", line 4, in prices = get_price_list(date(2015,1,1)) File "C:\Program Files (x86)\Python38-32\lib\site-packages\nsepy\history.py", line 309, in get_price_list txt = unzip_str(res.content) File "C:\Program Files (x86)\Python38-32\lib\site-packages\nsepy\commons.py", line 122, in unzip_str zf = zipfile.ZipFile(file=fp) File "C:\Program Files (x86)\Python38-32\lib\zipfile.py", line 1267, in **init** self._RealGetContents() File "C:\Program Files (x86)\Python38-32\lib\zipfile.py", line 1334, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> 
> > > >

Hi, did the issue fix for you, if so can you please tell me how you did it, thanks
