### ISSUE TITLE
API blocked for my IP address I guess

### ISSUE THREAD

**Issue by Manish6329** [swapniljariwala/nsepy#144]
Sir,
My code was working fine but today when I run the same program I got an error, is there any possibility that my IP get banned because for past few days I've been fetching data giving some hour of interval only.

Is there any way to get rid of this issue...  I'm trying to fetch the past 5 years data of all the stocks including future and option data for some research purposes, please do the need full. 
Even below simple code is giving the same error.

from nsepy import get_history
from datetime import date

data = get_history(symbol="SBIN", start=date(2015,1,1), end=date(2015,1,31))
print(data)

ERROR ARE AS BELOW:
C:\Users\manis\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/manis/PycharmProjects/AlgoTrading/checking.py
Traceback (most recent call last):
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x08225670>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www1.nseindia.com', port=80): Max retries exceeded with url: /products/dynaContent/common/productsSymbolMapping.jsp?dataType=PRICEVOLUMEDELIVERABLE&segmentLink=3&dateRange=&symbol=SBIN&series=EQ&symbolCount=1&fromDate=01-01-2015&toDate=31-01-2015 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x08225670>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/manis/PycharmProjects/AlgoTrading/checking.py", line 3, in <module>
    data = get_history(symbol="SBIN", start=date(2015,1,1), end=date(2015,1,31))
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nsepy\history.py", line 138, in get_history
    return get_history_quanta(**kwargs)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nsepy\history.py", line 146, in get_history_quanta
    headers=headers, scaling=scaling)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nsepy\history.py", line 151, in url_to_df
    resp = url(**params)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nsepy\commons.py", line 167, in __call__
    return self.session.get(url, params=kwargs, proxies = self.proxy )
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\manis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www1.nseindia.com', port=80): Max retries exceeded with url: /products/dynaContent/common/productsSymbolMapping.jsp?dataType=PRICEVOLUMEDELIVERABLE&segmentLink=3&dateRange=&symbol=SBIN&series=EQ&symbolCount=1&fromDate=01-01-2015&toDate=31-01-2015 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x08225670>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

Process finished with exit code 1

**Comment by swapniljariwala** [comment]
Can't help it, one solution is to keep your downloading script and analysis script separate.
* Use downloading script to download data and dump it to pickle
* In analysis script, read from the pickle so that you don't hit the NSE server every time you run analysis
