### ISSUE TITLE
Getting Empty data frame for equities

### ISSUE THREAD

**Issue by jayshahpy** [swapniljariwala/nsepy#156]
```
nifty_next50 = get_history(symbol="TCS",
                            start=date(2020,1,1),
                            end=date(2020,3,27),
                            index=True)
print (nifty_next50.head(50))
```

Tried above code and got below result:

```
Empty DataFrame
Columns: [Open, High, Low, Close, Volume, Turnover]
Index: []
```

Could you please help me resolve this issue? 

Even for more range of dates get similar error

```
nifty_next50 = get_history(symbol="TCS",
                            start=date(2008,1,1),
                            end=date(2020,1,1),
                            index=True)
```

```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Users\lenovo\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\lenovo\anaconda3\lib\site-packages\nsepy\commons.py", line 132, in run
    self.result = self._target(*self._args, **self._kwargs)
  File "C:\Users\lenovo\anaconda3\lib\site-packages\nsepy\history.py", line 136, in get_history
    return pd.concat((t1.result, t2.result))
AttributeError: 'ThreadReturns' object has no attribute 'result'

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, Turnover]
Index: []
```

**Comment by InnovArul** [comment]
your code works for me though. 
But I am getting empty frame for "PVR".

**Comment by jayshahpy** [comment]
Thank you for that!

Try PVR in lower case.

**Comment by jayshahpy** [comment]
I got it working with having Index = False since its not index's history that we are trying to fetch. 

Closing the issue

**Comment by InnovArul** [comment]
Thanks @jayshahpy. It worked with lowercase. strange. Do you know why its this way?
