### ISSUE TITLE
RuntimeError: Python 3.5 or later is required

### ISSUE THREAD

**Issue by dbazone** [swapniljariwala/nsepy#157]
I am getting below error while executing "pip install nsepy" command. I am using python 3.4.4. Can someone guide what could be the possible issue?

Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Projects\personal\nsepy\venv\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "e:\projects\personal\nsepy\venv\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "e:\projects\personal\nsepy\venv\lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "e:\projects\personal\nsepy\venv\lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "e:\projects\personal\nsepy\venv\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 24, in <module>
  File "e:\projects\personal\nsepy\venv\lib\site-packages\pip\_internal\cli\progress_bars.py", line 12, in <module>
    from pip._internal.utils.logging import get_indentation
  File "e:\projects\personal\nsepy\venv\lib\site-packages\pip\_internal\utils\logging.py", line 18, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "e:\projects\personal\nsepy\venv\lib\site-packages\pip\_internal\utils\misc.py", line 20, in <module>
    from pip._vendor import pkg_resources
  File "e:\projects\personal\nsepy\venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.5 or later is required")
RuntimeError: Python 3.5 or later is required

**Comment by strikar21** [comment]
Upgrade your python from 3.4.4 to 3.5 or later
