### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects

### ISSUE THREAD

**Issue by Jigisuta** [swapniljariwala/nsepy#250]
I also started getting this issue recently, it was working fine last month.

  File "C:\Users\nb\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects 
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
Code:

bhav_copy = get_price_list(dt=last_trade_date)
#last_trade_date is as the name suggests
I found a solution but I think it has to be implemented in the code of NSEPY, here is the link:
https://stackoverflow.com/questions/23651947/python-requests-requests-exceptions-toomanyredirects-exceeded-30-redirects

**Comment by aaryan-verma** [comment]
Please assign me this issue. I can solve it.

**Comment by jotinder** [comment]
This has totally broken my code. Requesting to please fix this on urgent basis.

**Comment by gmmkmtgk** [comment]
this is happening on my side also with any kind of usage of nsepy

C:\Users\gmmke\Desktop\new&information_automation>python infostock.py
Traceback (most recent call last):
  File "C:\Users\gmmke\Desktop\new&information_automation\infostock.py", line 3, in <module>
    quote = get_quote(symbol)
  File "C:\Users\gmmke\AppData\Local\Programs\Python\Python310\lib\site-packages\nsepy\live.py", line 56, in get_quote
    res = quote_eq_url(symbol, series)
  File "C:\Users\gmmke\AppData\Local\Programs\Python\Python310\lib\site-packages\nsepy\commons.py", line 167, in __call__
    return self.session.get(url, params=kwargs, proxies = self.proxy )
  File "C:\Users\gmmke\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\gmmke\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\gmmke\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "C:\Users\gmmke\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\gmmke\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

C:\Users\gmmke\Desktop\new&information_automation>

**Comment by manujchandra** [comment]
Hi, I am also facing the same issue. Last few weeks the library stopped working.

**Comment by suhas2686** [comment]
I did replace all the Nse old urls (www1.nse.com) with the new urls (www.nse.com). Yet the error continues. Weeding what could be the issue.

**Comment by tarunteckedge** [comment]
Hi, any updates on this please?

**Comment by jotinder** [comment]
@swapniljariwala we need your kind arrention to this. Can you please acknowledge this issue once, so we know whether to expect a solution to this issue in future or not. It's my humble request, so we can plan accordingly and spend efforts on using an alternate Api, in case with these URL change, it would not be possible to come up with a fix soon enough, which I can totally understand.

Requesting you to kindly just clear your stand on this issue.

Appreciate your efforts that went into making this API which has been a treat to use for many of us, so far.

Regards,
Jotinder

**Comment by prabhakarpandey76** [comment]
I was using it as well and now it is not working. Seems it is not free anymore. i see in NSE site quite heavy prices for this EOD data. can someone verify as well if this is the case? 

it will be very problematic if this will not be free........

**Comment by alloc7260** [comment]
Use this insted : [NSE-HISTORY-SCRAPER](https://github.com/alloc7260/NSE)

**Comment by pratik141** [comment]
created a new project for New NSE API

https://github.com/pratik141/nsedt

Soon add other APIs also
