### ISSUE TITLE
'ThreadReturns' object has no attribute 'result'

### ISSUE THREAD

**Issue by KshitizSharmaV** [swapniljariwala/nsepy#33]
Exception Type: AttributeError
Exception Value: 'ThreadReturns' object has no attribute 'result'
Exception Location: /Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/nsepy/history.py in get_history, line 130

This error doesn't occur always, sometimes it does, sometimes code works just fine. I can't make out what is it. I have already updated nsepy, can't resolve it yet.

using your library to build softwares on http://ktzcapitals.in, thanks for amazing work.

**Comment by KshitizSharmaV** [comment]
Here is the code, which is causing issue.

# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from nsepy import get_history, get_index_pe_history
from datetime import date
import pandas as pd

def pair_trading(request):
	nifty = get_history(symbol="NIFTY", 
                    start=date(2016,7,15), 
                    end=date(2017,7,14),
					index=True)
	bank_nifty = get_history(symbol="BANKNIFTY", 
                    start=date(2016,7,15), 
                    end=date(2017,7,14),
					index=True)

	nifty_high=nifty.High.tolist()
	bank_nifty_high=bank_nifty.High.tolist()
	#print nifty_high
	#print bank_nifty
	return render(request,'pair_trading.html',{'Nifty_High':nifty_high,'Bank_Nifty_High':bank_nifty_high,'title':"Pair Trading",'first_1':"Pair Trading Software",'second_2':"Pair Trading Algorihtm",'third_3':"Market Neual Strategy",'fourth_4':"What is Pair Trading"})

**Comment by KshitizSharmaV** [comment]
`from nsepy import get_history, get_index_pe_history
from datetime import date
import pandas as pd

def pair_trading(request):
	nifty = get_history(symbol="NIFTY", start=date(2016,7,15), end=date(2017,7,14),index=True)
	bank_nifty = get_history(symbol="BANKNIFTY", start=date(2016,7,15), end=date(2017,7,14), index=True)
	nifty_high=nifty.High.tolist()
	bank_nifty_high=bank_nifty.High.tolist()
	#print nifty_high
	#print bank_nifty
	return ("NSEPY")
`

**Comment by KshitizSharmaV** [comment]
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/nsepy/commons.py", line 130, in run
    self.result = self._Thread__target(*self._Thread__args, **self._Thread__kwargs)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/nsepy/history.py", line 133, in get_history
    return get_history_quanta(**kwargs)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/nsepy/history.py", line 142, in get_history_quanta
    headers=headers, scaling=scaling)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/nsepy/history.py", line 149, in url_to_df
    resp = url(**params)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/nsepy/commons.py", line 167, in __call__
    return self.session.get(url, params=kwargs, proxies = self.proxy )
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/requests/sessions.py", line 526, in get
    return self.request('GET', url, **kwargs)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

Internal Server Error: /pair_trading/
Traceback (most recent call last):
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/pair_trading/views.py", line 12, in pair_trading
    index=True)
  File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/nsepy/history.py", line 130, in get_history
    return pd.concat((t1.result, t2.result))
AttributeError: 'ThreadReturns' object has no attribute 'result'






I believe error is due to multiple requests to NSE website, but can't replicate the same issue when executing same commands on shell prompt. Do you know why is it happening ?

**Comment by swapniljariwala** [comment]
hey.. glad to see nsepy in use.. your website is impressive.. 
regarding error, get_history makes number of http requests in threads to nse's website, it looks like nse's website is not able to serve all the requests, my suggestion-
* try reducing date range
* store the data locally, avoid fetching data on every run, this will speed up your code as well


File "/Users/kshitizsharma/Desktop/ktzcapitals/ENV/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(54, _**'Connection reset by peer')**_

**Comment by KshitizSharmaV** [comment]
Okay thanks a lot for your suggestions, i will implement them.
