### ISSUE TITLE
FII python example error

### ISSUE THREAD

**Issue by csayantan** [swapniljariwala/nsepy#8]
```
:~$ python FII.py
Traceback (most recent call last):
  File "FII.py", line 9, in <module>
    from nsepy.archive import html_to_rows
ImportError: No module named nsepy.archive
```

```

# -*- coding: utf-8 -*-
"""
Created on Sun Sep 27 17:35:16 2015

@author: jerry
"""

import requests
from nsepy.archive import html_to_rows
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
FII_YEARLY_URL = 'https://www.fpi.nsdl.co.in/web/Reports/Yearwise.aspx?RptType=5'

def fii_yearly():
    resp = requests.get(FII_YEARLY_URL, verify = False)
    soup = BeautifulSoup(resp.text)
    ts = soup.find_all('table')
    trs = ts[1].find_all('tr')
    del trs[0]
    del trs[0]
    del trs[0]
    trs.pop()
    xs = []
    arr = np.empty([3,len(trs)])
    r_cnt = 0
    for r in trs:
        cs = r.find_all('td')
        c_cnt = 0
        for c in cs:
            if c_cnt == 1:
                pass
            if c_cnt > 0:
                arr[c_cnt - 1, r_cnt] = np.float(c.text)
            c_cnt += 1
        r_cnt += 1           
    return arr

if __name__ == "__main__":
    d = fii_yearly()


```

having error please suggest.

**Comment by csayantan** [comment]
this issue resolved but can we have a ploting of FII and DII data?

**Comment by swapniljariwala** [comment]
Can you please check now FII.py

**Comment by csayantan** [comment]
```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "FII.py", line 41, in <module>
    d.plot()
AttributeError: 'numpy.ndarray' object has no attribute 'plot'
```

**Comment by swapniljariwala** [comment]
yeah.. I'll look into warnings but did it plot?

**Comment by csayantan** [comment]
no it dzn't.

**Comment by swapniljariwala** [comment]
Thanks for trying out. I've been busy with office lately. Hopefully I can have a look in this month.
