### ISSUE TITLE
nsepy.get_history giving error

### ISSUE THREAD

**Issue by ssashita** [swapniljariwala/nsepy#88]
I am using nespy v 0.7 with python 3.5. This is the error when I use
nse.get_history(symbol='NIFTY', index=True,start=dt.date(2013,1,1), end=dt.date(2018,11,23))

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/site-packages/nsepy/commons.py", line 132, in run
    self.result = self._target(*self._args, **self._kwargs)
TypeError: get_history() got an unexpected keyword argument 'kwargs1'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/site-packages/nsepy/commons.py", line 132, in run
    self.result = self._target(*self._args, **self._kwargs)
TypeError: get_history() got an unexpected keyword argument 'kwargs'

Traceback (most recent call last):
  File "/home/ssashita/zambala-backend/scripts/nse.py", line 41, in <module>
    data['NIFTY'] = nse.get_history(symbol='NIFTY', index=True,start=dt.date(2013,1,1), end=dt.date(2018,11,23))
  File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/site-packages/nsepy/history.py", line 133, in get_history
    return pd.concat((t1.result, t2.result))
AttributeError: 'ThreadReturns' object has no attribute 'result'

**Comment by ssashita** [comment]
Thanks for the response. Saw it only now.

**Comment by kd161298** [comment]
> I am using nespy v 0.7 with python 3.5. This is the error when I use
> nse.get_history(symbol='NIFTY', index=True,start=dt.date(2013,1,1), end=dt.date(2018,11,23))
> 
> Exception in thread Thread-2:
> Traceback (most recent call last):
> File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/threading.py", line 914, in _bootstrap_inner
> self.run()
> File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/site-packages/nsepy/commons.py", line 132, in run
> self.result = self._target(*self._args, **self._kwargs)
> TypeError: get_history() got an unexpected keyword argument 'kwargs1'
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/threading.py", line 914, in _bootstrap_inner
> self.run()
> File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/site-packages/nsepy/commons.py", line 132, in run
> self.result = self._target(*self._args, **self._kwargs)
> TypeError: get_history() got an unexpected keyword argument 'kwargs'
> 
> Traceback (most recent call last):
> File "/home/ssashita/zambala-backend/scripts/nse.py", line 41, in 
> data['NIFTY'] = nse.get_history(symbol='NIFTY', index=True,start=dt.date(2013,1,1), end=dt.date(2018,11,23))
> File "/home/ssashita/anaconda3/envs/python3env/lib/python3.5/site-packages/nsepy/history.py", line 133, in get_history
> return pd.concat((t1.result, t2.result))
> AttributeError: 'ThreadReturns' object has no attribute 'result'

I am getting the same error..please tell the solution if u solved this error..

**Comment by kd161298** [comment]
I am getting the same error..please tell the solution if u solved this error..

**Comment by ssashita** [comment]
> I am getting the same error..please tell the solution if u solved this error..

Hi,
I just tried it on python 3.5.6 and it is fetching the results for me alright

import nsepy as nse
import datetime as dt
nse.get_history(symbol='NIFTY 50', index=True, start=dt.date(2013,1,1), end=dt.date(2018,11,23))

#Even symbol='NIFTY' is working for me now !

**Comment by atishayjain708** [comment]
Python 3.4.7;
Facing the same error. However, a peculiarity is, the error occurs only when trying to fetch data for a longer period. What I mean to say is,
```
df = get_history(symbol="SBIN", start=date(2015,1,1), end=date(2018,1,31))
```
gives the above error. 
While, 
```
df = get_history(symbol="SBIN", start=date(2015,1,1), end=date(2016,1,31))
``` seems to work just fine. Any suggestions?

**Comment by SRUTHY-K** [comment]
I am getting this error now. Could you please help?

**Comment by ghoshsudipto** [comment]
> Python 3.7.4;
> Facing the same error. However, a peculiarity is, the error occurs only when trying to fetch data for a longer period. What I mean to say is,
> 
> ```
> df = get_history(symbol="SBIN", start=date(2015,1,1), end=date(2018,1,31))
> ```
> 
> gives the above error.
> While,
> 
> ```
> df = get_history(symbol="SBIN", start=date(2015,1,1), end=date(2016,1,31))
> ```
> 
> seems to work just fine. Any suggestions?

This error is due to connectivity. Either nse server got some issue or internet issue.
I am facing the same issue, but after trying 6-7 times it works.

**Comment by UditGupta10** [comment]
I am getting the 'Thread returns' error for get_index_pe_history. Works fine for 'NIFTY 50', but not for any other indices such as 'NIFTY NEXT 50'.

**Comment by GandharN** [comment]
Turns out this error happens because of connection issues.
Heres a workaround

while True:
    try:
        get_history
    except AttributeError:
        continue

**Comment by odinsonthor10** [comment]
It's a connection issue. I tried 7-8 times and connected to a faster network and the problem is solved

**Comment by p335-43** [comment]
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?0e588490-04b5-4102-a81f-cc7774b4c989)Exception in thread Thread-20:
Traceback (most recent call last):
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/threading.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/threading.py)", line 926, in _bootstrap_inner
    self.run()
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/commons.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/commons.py)", line 132, in run
    self.result = self._target(*self._args, **self._kwargs)
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py)", line 138, in get_history
    return get_history_quanta(**kwargs)
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py)", line 146, in get_history_quanta
    headers=headers, scaling=scaling)
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py)", line 151, in url_to_df
    resp = url(**params)
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/commons.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/commons.py)", line 167, in __call__
    return self.session.get(url, params=kwargs, proxies = self.proxy )
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py)", line 600, in get
    return self.request("GET", url, **kwargs)
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py)", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py)", line 723, in send
    history = [resp for resp in gen]
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py)", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/requests/sessions.py)", line 192, in resolve_redirects
    f"Exceeded {self.max_redirects} redirects.", response=resp
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
...
  File "[/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py)", line 136, in get_history
    return pd.concat((t1.result, t2.result))
AttributeError: 'ThreadReturns' object has no attribute 'result'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/var/folders/jf/26_1w2qs0pqfylxdlsny15180000gn/T/ipykernel_43037/893248395.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/jf/26_1w2qs0pqfylxdlsny15180000gn/T/ipykernel_43037/893248395.py) in 
----> 1 raw_data = get_history(symbol=symbol, start=start, end=end)
      2 # raw_data.reset_index(inplace=True)
      3 raw_data

[~/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py](https://file+.vscode-resource.vscode-cdn.net/Users/pranjalmishra/Desktop/myprograms/pyhton/~/opt/anaconda3/envs/pranjal/lib/python3.7/site-packages/nsepy/history.py) in get_history(symbol, start, end, index, futures, option_type, expiry_date, strike_price, series)
    134         t1.join()
    135         t2.join()
--> 136         return pd.concat((t1.result, t2.result))
    137     else:
    138         return get_history_quanta(**kwargs)

AttributeError: 'ThreadReturns' object has no attribute 'result'

again same error has came.plz give some suggestios to solve this

**Comment by Jigisuta** [comment]
I also started getting this issue recently, it was working fine last month. 

```
  File "C:\Users\nb\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects 
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

```
Code:

bhav_copy = get_price_list(dt=last_trade_date)
#last_trade_date is as the name suggests
```

I found a solution but I think it has to be implemented in the code of NSEPY, here is the link:
https://stackoverflow.com/questions/23651947/python-requests-requests-exceptions-toomanyredirects-exceeded-30-redirects

**Should we start a new issue thread based on this?**

**Comment by p335-43** [comment]
i think you should start a new api for this

**Comment by jotinder** [comment]
Am also facing the same issue which can be traced down to get_history. Can someone please share a working solution. 

G:\Jotinder\Market_Watch\venv\Scripts\python.exe G:/Jotinder/Market_Watch/Wrapper.py
2023-04-21
Traceback (most recent call last):
  File "G:/Jotinder/Market_Watch/Wrapper.py", line 44, in <module>
    df = calculate_lms_hmr.calculate_lms_hmr(df,dict_file)
  File "G:\Jotinder\Market_Watch\calculate_lms_hmr.py", line 22, in calculate_lms_hmr
    low_high_lst = self.nse_data.nse_data(stock)
  File "G:\Jotinder\Market_Watch\NSE_Data.py", line 34, in nse_data
    index_df = get_history(stock,start=self.curr_date,end=self.curr_date)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nsepy\history.py", line 138, in get_history
    return get_history_quanta(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nsepy\history.py", line 146, in get_history_quanta
    headers=headers, scaling=scaling)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nsepy\history.py", line 151, in url_to_df
    resp = url(**params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nsepy\commons.py", line 167, in __call__
    return self.session.get(url, params=kwargs, proxies = self.proxy )
  File "C:\Users\my pc\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\my pc\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\my pc\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\my pc\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\my pc\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.


Code causing this error--> 
index_df = get_history(stock,start=self.curr_date,end=self.curr_date)

tried manually as well and got the same error.

**Comment by kgsatish** [comment]
Try [nselib](https://github.com/RuchiTanmay/nselib). It works!
