### ISSUE TITLE
 AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_CMS'

### ISSUE THREAD

**Issue by arunsivaraj** [swapniljariwala/nsepy#89]
Hi All, I am getting below while executing my script.  I was able to get the data perfectly untill yesterday but now suddenly it stopped working.

Traceback (most recent call last):
  File "C:/AASR/Prsnl_Work/analysis.py", line 4, in <module>
    from nsepy import get_history
  File "C:\Python36\lib\site-packages\nsepy\__init__.py", line 1, in <module>
    from .history import get_history, get_index_pe_history, get_rbi_ref_history
  File "C:\Python36\lib\site-packages\nsepy\history.py", line 8, in <module>
    from nsepy.urls import *
  File "C:\Python36\lib\site-packages\nsepy\urls.py", line 8, in <module>
    from nsepy.commons import URLFetch
  File "C:\Python36\lib\site-packages\nsepy\commons.py", line 7, in <module>
    import requests
  File "C:\Python36\lib\site-packages\requests\__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "C:\Python36\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "C:\Python36\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Python36\lib\site-packages\OpenSSL\crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "C:\Python36\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Python36\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "C:\Python36\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "C:\Python36\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "C:\Python36\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 84, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_CMS'

**Comment by arunsivaraj** [comment]
After reinstalling python, this issue is fixed.
